[2024-03-18 19:57:02,781] {processor.py:153} INFO - Started process (PID=1989985) to work on /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 19:57:02,781] {processor.py:641} INFO - Processing file /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-18 19:57:02,782] {logging_mixin.py:115} INFO - [2024-03-18 19:57:02,782] {dagbag.py:507} INFO - Filling up the DagBag from /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 19:57:02,794] {logging_mixin.py:115} INFO - [2024-03-18 19:57:02,793] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-18 19:57:02,794] {logging_mixin.py:115} INFO - [2024-03-18 19:57:02,794] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-18 19:57:02,794] {processor.py:653} WARNING - No viable dags retrieved from /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 19:57:02,803] {processor.py:161} INFO - Processing /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-03-18 19:57:42,598] {processor.py:153} INFO - Started process (PID=1990385) to work on /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 19:57:42,599] {processor.py:641} INFO - Processing file /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-18 19:57:42,600] {logging_mixin.py:115} INFO - [2024-03-18 19:57:42,600] {dagbag.py:507} INFO - Filling up the DagBag from /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 19:57:42,625] {logging_mixin.py:115} INFO - [2024-03-18 19:57:42,625] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-18 19:57:42,625] {logging_mixin.py:115} INFO - [2024-03-18 19:57:42,625] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-18 19:57:42,626] {processor.py:653} WARNING - No viable dags retrieved from /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 19:57:42,634] {processor.py:161} INFO - Processing /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-03-18 19:58:15,457] {processor.py:153} INFO - Started process (PID=1990703) to work on /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 19:58:15,463] {processor.py:641} INFO - Processing file /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-18 19:58:15,463] {logging_mixin.py:115} INFO - [2024-03-18 19:58:15,463] {dagbag.py:507} INFO - Filling up the DagBag from /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 19:58:15,479] {logging_mixin.py:115} INFO - [2024-03-18 19:58:15,479] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-18 19:58:15,480] {logging_mixin.py:115} INFO - [2024-03-18 19:58:15,480] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-18 19:58:15,480] {processor.py:653} WARNING - No viable dags retrieved from /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 19:58:15,490] {processor.py:161} INFO - Processing /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2024-03-18 19:58:49,609] {processor.py:153} INFO - Started process (PID=1991047) to work on /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 19:58:49,614] {processor.py:641} INFO - Processing file /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-18 19:58:49,615] {logging_mixin.py:115} INFO - [2024-03-18 19:58:49,615] {dagbag.py:507} INFO - Filling up the DagBag from /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 19:58:49,632] {logging_mixin.py:115} INFO - [2024-03-18 19:58:49,632] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-18 19:58:49,632] {logging_mixin.py:115} INFO - [2024-03-18 19:58:49,632] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-18 19:58:49,632] {processor.py:653} WARNING - No viable dags retrieved from /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 19:58:49,645] {processor.py:161} INFO - Processing /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2024-03-18 19:59:21,494] {processor.py:153} INFO - Started process (PID=1991373) to work on /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 19:59:21,498] {processor.py:641} INFO - Processing file /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-18 19:59:21,498] {logging_mixin.py:115} INFO - [2024-03-18 19:59:21,498] {dagbag.py:507} INFO - Filling up the DagBag from /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 19:59:21,506] {logging_mixin.py:115} INFO - [2024-03-18 19:59:21,506] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-18 19:59:21,506] {logging_mixin.py:115} INFO - [2024-03-18 19:59:21,506] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-18 19:59:21,506] {processor.py:653} WARNING - No viable dags retrieved from /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 19:59:21,513] {processor.py:161} INFO - Processing /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2024-03-18 19:59:55,836] {processor.py:153} INFO - Started process (PID=1991732) to work on /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 19:59:55,837] {processor.py:641} INFO - Processing file /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-18 19:59:55,838] {logging_mixin.py:115} INFO - [2024-03-18 19:59:55,838] {dagbag.py:507} INFO - Filling up the DagBag from /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 19:59:55,863] {logging_mixin.py:115} INFO - [2024-03-18 19:59:55,862] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-18 19:59:55,863] {logging_mixin.py:115} INFO - [2024-03-18 19:59:55,863] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-18 19:59:55,863] {processor.py:653} WARNING - No viable dags retrieved from /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 19:59:55,874] {processor.py:161} INFO - Processing /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-03-18 20:00:30,026] {processor.py:153} INFO - Started process (PID=1992146) to work on /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 20:00:30,032] {processor.py:641} INFO - Processing file /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-18 20:00:30,033] {logging_mixin.py:115} INFO - [2024-03-18 20:00:30,033] {dagbag.py:507} INFO - Filling up the DagBag from /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 20:00:30,066] {logging_mixin.py:115} INFO - [2024-03-18 20:00:30,065] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-18 20:00:30,066] {logging_mixin.py:115} INFO - [2024-03-18 20:00:30,066] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-18 20:00:30,066] {processor.py:653} WARNING - No viable dags retrieved from /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 20:00:30,077] {processor.py:161} INFO - Processing /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.057 seconds
[2024-03-18 20:01:03,378] {processor.py:153} INFO - Started process (PID=1992480) to work on /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 20:01:03,384] {processor.py:641} INFO - Processing file /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-18 20:01:03,386] {logging_mixin.py:115} INFO - [2024-03-18 20:01:03,386] {dagbag.py:507} INFO - Filling up the DagBag from /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 20:01:03,419] {logging_mixin.py:115} INFO - [2024-03-18 20:01:03,418] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-18 20:01:03,419] {logging_mixin.py:115} INFO - [2024-03-18 20:01:03,419] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-18 20:01:03,419] {processor.py:653} WARNING - No viable dags retrieved from /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 20:01:03,428] {processor.py:161} INFO - Processing /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2024-03-18 20:01:35,463] {processor.py:153} INFO - Started process (PID=1992795) to work on /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 20:01:35,466] {processor.py:641} INFO - Processing file /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-18 20:01:35,466] {logging_mixin.py:115} INFO - [2024-03-18 20:01:35,466] {dagbag.py:507} INFO - Filling up the DagBag from /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 20:01:35,477] {logging_mixin.py:115} INFO - [2024-03-18 20:01:35,477] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-18 20:01:35,477] {logging_mixin.py:115} INFO - [2024-03-18 20:01:35,477] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-18 20:01:35,477] {processor.py:653} WARNING - No viable dags retrieved from /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 20:01:35,485] {processor.py:161} INFO - Processing /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-03-18 20:02:08,184] {processor.py:153} INFO - Started process (PID=1993150) to work on /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 20:02:08,185] {processor.py:641} INFO - Processing file /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-18 20:02:08,185] {logging_mixin.py:115} INFO - [2024-03-18 20:02:08,185] {dagbag.py:507} INFO - Filling up the DagBag from /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 20:02:08,197] {logging_mixin.py:115} INFO - [2024-03-18 20:02:08,196] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-18 20:02:08,197] {logging_mixin.py:115} INFO - [2024-03-18 20:02:08,197] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-18 20:02:08,197] {processor.py:653} WARNING - No viable dags retrieved from /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 20:02:08,203] {processor.py:161} INFO - Processing /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2024-03-18 20:02:40,393] {processor.py:153} INFO - Started process (PID=1993475) to work on /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 20:02:40,398] {processor.py:641} INFO - Processing file /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-18 20:02:40,399] {logging_mixin.py:115} INFO - [2024-03-18 20:02:40,399] {dagbag.py:507} INFO - Filling up the DagBag from /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 20:02:40,416] {logging_mixin.py:115} INFO - [2024-03-18 20:02:40,416] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-18 20:02:40,416] {logging_mixin.py:115} INFO - [2024-03-18 20:02:40,416] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-18 20:02:40,417] {processor.py:653} WARNING - No viable dags retrieved from /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 20:02:40,423] {processor.py:161} INFO - Processing /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2024-03-18 20:03:13,683] {processor.py:153} INFO - Started process (PID=1993811) to work on /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 20:03:13,686] {processor.py:641} INFO - Processing file /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-18 20:03:13,687] {logging_mixin.py:115} INFO - [2024-03-18 20:03:13,687] {dagbag.py:507} INFO - Filling up the DagBag from /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 20:03:13,709] {logging_mixin.py:115} INFO - [2024-03-18 20:03:13,708] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-18 20:03:13,709] {logging_mixin.py:115} INFO - [2024-03-18 20:03:13,709] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-18 20:03:13,709] {processor.py:653} WARNING - No viable dags retrieved from /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 20:03:13,720] {processor.py:161} INFO - Processing /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2024-03-18 20:03:46,731] {processor.py:153} INFO - Started process (PID=1994140) to work on /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 20:03:46,736] {processor.py:641} INFO - Processing file /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-18 20:03:46,736] {logging_mixin.py:115} INFO - [2024-03-18 20:03:46,736] {dagbag.py:507} INFO - Filling up the DagBag from /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 20:03:46,752] {logging_mixin.py:115} INFO - [2024-03-18 20:03:46,751] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-18 20:03:46,752] {logging_mixin.py:115} INFO - [2024-03-18 20:03:46,752] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-18 20:03:46,752] {processor.py:653} WARNING - No viable dags retrieved from /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 20:03:46,759] {processor.py:161} INFO - Processing /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2024-03-18 20:04:20,339] {processor.py:153} INFO - Started process (PID=1994465) to work on /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 20:04:20,345] {processor.py:641} INFO - Processing file /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-18 20:04:20,346] {logging_mixin.py:115} INFO - [2024-03-18 20:04:20,346] {dagbag.py:507} INFO - Filling up the DagBag from /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 20:04:20,378] {logging_mixin.py:115} INFO - [2024-03-18 20:04:20,377] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-18 20:04:20,378] {logging_mixin.py:115} INFO - [2024-03-18 20:04:20,378] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-18 20:04:20,378] {processor.py:653} WARNING - No viable dags retrieved from /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 20:04:20,385] {processor.py:161} INFO - Processing /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.053 seconds
[2024-03-18 20:04:53,261] {processor.py:153} INFO - Started process (PID=1994805) to work on /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 20:04:53,267] {processor.py:641} INFO - Processing file /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-18 20:04:53,268] {logging_mixin.py:115} INFO - [2024-03-18 20:04:53,268] {dagbag.py:507} INFO - Filling up the DagBag from /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 20:04:53,291] {logging_mixin.py:115} INFO - [2024-03-18 20:04:53,291] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-18 20:04:53,291] {logging_mixin.py:115} INFO - [2024-03-18 20:04:53,291] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-18 20:04:53,291] {processor.py:653} WARNING - No viable dags retrieved from /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 20:04:53,298] {processor.py:161} INFO - Processing /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-03-18 20:05:26,467] {processor.py:153} INFO - Started process (PID=1995140) to work on /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 20:05:26,473] {processor.py:641} INFO - Processing file /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-18 20:05:26,474] {logging_mixin.py:115} INFO - [2024-03-18 20:05:26,474] {dagbag.py:507} INFO - Filling up the DagBag from /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 20:05:26,504] {logging_mixin.py:115} INFO - [2024-03-18 20:05:26,503] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-18 20:05:26,504] {logging_mixin.py:115} INFO - [2024-03-18 20:05:26,504] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-18 20:05:26,504] {processor.py:653} WARNING - No viable dags retrieved from /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 20:05:26,511] {processor.py:161} INFO - Processing /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.053 seconds
[2024-03-18 20:05:59,825] {processor.py:153} INFO - Started process (PID=1995568) to work on /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 20:05:59,830] {processor.py:641} INFO - Processing file /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-18 20:05:59,830] {logging_mixin.py:115} INFO - [2024-03-18 20:05:59,830] {dagbag.py:507} INFO - Filling up the DagBag from /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 20:05:59,845] {logging_mixin.py:115} INFO - [2024-03-18 20:05:59,845] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-18 20:05:59,846] {logging_mixin.py:115} INFO - [2024-03-18 20:05:59,845] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-18 20:05:59,846] {processor.py:653} WARNING - No viable dags retrieved from /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 20:05:59,853] {processor.py:161} INFO - Processing /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2024-03-18 20:06:32,492] {processor.py:153} INFO - Started process (PID=1995904) to work on /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 20:06:32,497] {processor.py:641} INFO - Processing file /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-18 20:06:32,497] {logging_mixin.py:115} INFO - [2024-03-18 20:06:32,497] {dagbag.py:507} INFO - Filling up the DagBag from /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 20:06:32,516] {logging_mixin.py:115} INFO - [2024-03-18 20:06:32,516] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-18 20:06:32,516] {logging_mixin.py:115} INFO - [2024-03-18 20:06:32,516] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-18 20:06:32,516] {processor.py:653} WARNING - No viable dags retrieved from /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 20:06:32,526] {processor.py:161} INFO - Processing /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2024-03-18 20:07:08,564] {processor.py:153} INFO - Started process (PID=1996284) to work on /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 20:07:08,571] {processor.py:641} INFO - Processing file /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-18 20:07:08,572] {logging_mixin.py:115} INFO - [2024-03-18 20:07:08,572] {dagbag.py:507} INFO - Filling up the DagBag from /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 20:07:08,602] {logging_mixin.py:115} INFO - [2024-03-18 20:07:08,602] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-18 20:07:08,602] {logging_mixin.py:115} INFO - [2024-03-18 20:07:08,602] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-18 20:07:08,602] {processor.py:653} WARNING - No viable dags retrieved from /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 20:07:08,610] {processor.py:161} INFO - Processing /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.053 seconds
[2024-03-18 20:07:41,642] {processor.py:153} INFO - Started process (PID=1996896) to work on /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 20:07:41,647] {processor.py:641} INFO - Processing file /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-18 20:07:41,648] {logging_mixin.py:115} INFO - [2024-03-18 20:07:41,648] {dagbag.py:507} INFO - Filling up the DagBag from /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 20:07:41,661] {logging_mixin.py:115} INFO - [2024-03-18 20:07:41,661] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-18 20:07:41,661] {logging_mixin.py:115} INFO - [2024-03-18 20:07:41,661] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-18 20:07:41,662] {processor.py:653} WARNING - No viable dags retrieved from /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 20:07:41,671] {processor.py:161} INFO - Processing /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2024-03-18 20:08:15,989] {processor.py:153} INFO - Started process (PID=1997757) to work on /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 20:08:15,994] {processor.py:641} INFO - Processing file /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-18 20:08:15,995] {logging_mixin.py:115} INFO - [2024-03-18 20:08:15,995] {dagbag.py:507} INFO - Filling up the DagBag from /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 20:08:16,007] {logging_mixin.py:115} INFO - [2024-03-18 20:08:16,007] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-18 20:08:16,007] {logging_mixin.py:115} INFO - [2024-03-18 20:08:16,007] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-18 20:08:16,007] {processor.py:653} WARNING - No viable dags retrieved from /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 20:08:16,015] {processor.py:161} INFO - Processing /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2024-03-18 20:08:50,722] {processor.py:153} INFO - Started process (PID=1998472) to work on /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 20:08:50,727] {processor.py:641} INFO - Processing file /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-18 20:08:50,728] {logging_mixin.py:115} INFO - [2024-03-18 20:08:50,728] {dagbag.py:507} INFO - Filling up the DagBag from /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 20:08:50,737] {logging_mixin.py:115} INFO - [2024-03-18 20:08:50,737] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-18 20:08:50,738] {logging_mixin.py:115} INFO - [2024-03-18 20:08:50,738] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-18 20:08:50,738] {processor.py:653} WARNING - No viable dags retrieved from /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-18 20:08:50,744] {processor.py:161} INFO - Processing /home/sheyla/Documents/Repositórios/apache-airflow-extracao-de-dados/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
